import type { Category } from '../types/category';
import type { Ingredient } from '../types/ingredients';

export const ingredientMap = {
    'THM Baking Blend': 'Baking Mix' as Category,
    'THM Gentle Sweet': 'Seasoning & Extracts' as Category,
    'THM Creamy Dreamy Hemp Protein': 'Protein' as Category,
    Erythritol: 'Seasoning & Extracts' as Category,
    'Cocoa Powder': 'Baking' as Category,
    'Baking Powder': 'Baking' as Category,
    'Baking Soda': 'Baking' as Category,
    'Mineral Salt': 'Seasoning & Extracts' as Category,
    'Almond Milk': 'Dairy / Non-Dairy' as Category,
    'Cashew Milk': 'Dairy / Non-Dairy' as Category,
    'Coconut Milk': 'Dairy / Non-Dairy' as Category,
    'Flax Milk': 'Dairy / Non-Dairy' as Category,
    'Unsweetened Nut Milk': 'Dairy / Non-Dairy' as Category,
    'Unsweetened Milk': 'Dairy / Non-Dairy' as Category,
    'Nut Milk': 'Dairy / Non-Dairy' as Category,
    'Apple Cider Vinegar': 'Vinegar & Oil' as Category,
    'White Vinegar': 'Vinegar & Oil' as Category,
    Yogurt: 'Dairy / Non-Dairy' as Category,
    'Coconut Oil': 'Oil' as Category,
    'Extra Virgin Coconut Oil': 'Oil' as Category,
    'Unsweetened Baking Chocolate': 'Baking' as Category,
    Stevia: 'Seasoning & Extracts' as Category,
    'Caramel Extract': 'Seasoning & Extracts' as Category,
    'Butter Extract': 'Seasoning & Extracts' as Category,
    'Maple Extract': 'Seasoning & Extracts' as Category,
    'Vanilla Extract': 'Seasoning & Extracts' as Category,
    'Chopped Pecans': 'Nuts & Seeds' as Category,
    Apple: 'Fruits & Vegetables' as Category,
    Cinnamon: 'Seasoning & Extracts' as Category,
    'Old Fashioned Oats': 'Fiber & Grains' as Category,
    'Steel Cut Oats': 'Fiber & Grains' as Category,
    'Psyllium Flakes': 'Fiber & Grains' as Category,
    'Ground Flaxseed': 'Fiber & Grains' as Category,
    'Egg Whites': 'Protein' as Category,
    Raisins: 'Fruits & Vegetables' as Category,
    'Unsweetened Applesauce': 'Fruits & Vegetables' as Category,
    Avocados: 'Fruits & Vegetables' as Category,
    Eggs: 'Protein' as Category,
    'Integral Collagen': 'Protein Powder' as Category,
    'Chocolate Chips': 'Baking' as Category,
    'Salad Mix': 'Fruits & Vegetables' as Category,
    'Chopped Romaine': 'Fruits & Vegetables' as Category,
    Tomatoes: 'Fruits & Vegetables' as Category,
    Bacon: 'Protein' as Category,
    Mayonnaise: 'Vinegar & Oil' as Category,
    'Black Pepper': 'Seasoning & Extracts' as Category,
    'Shredded Cheddar': 'Dairy / Non-Dairy' as Category,
    Bananas: 'Fruits & Vegetables' as Category,
    Cocoa: 'Baking' as Category,
    'Chicken Breasts': 'Protein' as Category,
    'Garlic Powder': 'Seasoning & Extracts' as Category,
    'Romaine Lettuce': 'Fruits & Vegetables' as Category,
    'Goat Cheese': 'Dairy / Non-Dairy' as Category,
    Strawberries: 'Fruits & Vegetables' as Category,
    'Easy Balsamic Glaze': 'Vinegar & Oil' as Category,
    'Sugar Free Balsamic Vinegar': 'Vinegar & Oil' as Category,
};

export const ingredients = Object.entries(ingredientMap)
    .map(([i, c]) => ({
        ingredient: i as Ingredient,
        category: c as Category,
    }))
    .sort((a, b) => (a.ingredient < b.ingredient ? -1 : a.ingredient > b.ingredient ? 1 : 0));
