export const ingredientMap = {
    'Briana Thomas Baking Mix': 'Baking' as const,
    'THM Baking Blend': 'Baking' as const,
    'Cocoa Powder': 'Baking' as const,
    'Just Gelatin': 'Baking' as const,
    'Baking Powder': 'Baking' as const,
    'Baking Soda': 'Baking' as const,
    'Cocoa Butter': 'Baking' as const,
    'Unsweetened Baking Chocolate': 'Baking' as const,
    'Cauliflower Flour': 'Baking' as const,
    'Glucomannan Powder': 'Baking' as const,
    'Almond Flour': 'Baking' as const,
    'Coconut Flour': 'Baking' as const,
    'Sourdough Discard': 'Baking' as const,
    'Coconut Manna': 'Baking' as const,
    'Sprouted Flour': 'Baking' as const,
    'Cinnamon Baking Chips': 'Baking' as const,
    'Peppermint Chips': 'Baking' as const,
    'Black Strap Molasses': 'Baking' as const,
    'Coconut Butter': 'Baking' as const,
    'Unsweetened Coconut Flakes': 'Baking' as const,
    Chocolate: 'Baking' as const,
    'Raw Honey': 'Seasoning & Extracts' as const,
    Truvia: 'Seasoning & Extracts' as const,
    Pyure: 'Seasoning & Extracts' as const,
    'THM Super Sweet': 'Seasoning & Extracts' as const,
    'THM Gentle Sweet': 'Seasoning & Extracts' as const,
    'Pepper': 'Seasoning & Extracts' as const,
    Erythritol: 'Seasoning & Extracts' as const,
    'Cake Batter Extract': 'Seasoning & Extracts' as const,
    'Mineral Salt': 'Seasoning & Extracts' as const,
    Butter: 'Dairy / Non-Dairy' as const,
    "My Montana Kitchen's Sweetened Condensed Milk": 'Dairy / Non-Dairy' as const,
    'Yogurt Cultures': 'Dairy / Non-Dairy' as const,
    'Unsweetened Almond Milk': 'Dairy / Non-Dairy' as const,
    'Sweetened Condensed Milk': 'Dairy / Non-Dairy' as const,
    'Blue Cheese Crumbles': 'Dairy / Non-Dairy' as const,
    'Low-fat Greek Yogurt': 'Dairy / Non-Dairy' as const,
    'Shredded Cheddar': 'Dairy / Non-Dairy' as const,
    'Dairy Free Yogurt': 'Dairy / Non-Dairy' as const,
    'Almond Milk': 'Dairy / Non-Dairy' as const,
    'Sour Cream': 'Dairy / Non-Dairy' as const,
    'Cashew Milk': 'Dairy / Non-Dairy' as const,
    'Goat Cheese': 'Dairy / Non-Dairy' as const,
    'Coconut Milk': 'Dairy / Non-Dairy' as const,
    'Flax Milk': 'Dairy / Non-Dairy' as const,
    'Unsweetened Nut Milk': 'Dairy / Non-Dairy' as const,
    'Unsweetened Milk': 'Dairy / Non-Dairy' as const,
    'Nut Milk': 'Dairy / Non-Dairy' as const,
    Yogurt: 'Dairy / Non-Dairy' as const,
    'Olive Oil': 'Vinegar & Oil' as const,
    'Apple Cider Vinegar': 'Vinegar & Oil' as const,
    'White Vinegar': 'Vinegar & Oil' as const,
    Mayonnaise: 'Vinegar & Oil' as const,
    'MCT Oil': 'Vinegar & Oil' as const,
    'Easy Balsamic Glaze': 'Vinegar & Oil' as const,
    'Sugar Free Balsamic Vinegar': 'Vinegar & Oil' as const,
    'Avocado Oil': 'Vinegar & Oil' as const,
    'High Heat Oil': 'Vinegar & Oil' as const,
    'Coconut Oil': 'Vinegar & Oil' as const,
    'Extra Virgin Coconut Oil': 'Vinegar & Oil' as const,
    Stevia: 'Seasoning & Extracts' as const,
    'Chili Powder': 'Seasoning & Extracts' as const,
    Paprika: 'Seasoning & Extracts' as const,
    Cumin: 'Seasoning & Extracts' as const,
    Salt: 'Seasoning & Extracts' as const,
    'THM Duo Greens': 'Seasoning & Extracts' as const,
    'Nutritional Yeast': 'Seasoning & Extracts' as const,
    'Baobab Powder': 'Seasoning & Extracts' as const,
    'Caramel Extract': 'Seasoning & Extracts' as const,
    'Butter Extract': 'Seasoning & Extracts' as const,
    'Garlic Powder': 'Seasoning & Extracts' as const,
    'Maple Extract': 'Seasoning & Extracts' as const,
    'Vanilla Extract': 'Seasoning & Extracts' as const,
    'Onion Powder': 'Seasoning & Extracts' as const,
    Parsley: 'Seasoning & Extracts' as const,
    'Cayenne Pepper': 'Seasoning & Extracts' as const,
    Cinnamon: 'Seasoning & Extracts' as const,
    Raisins: 'Fruits & Vegetables' as const,
    Avocados: 'Fruits & Vegetables' as const,
    Cauliflower: 'Fruits & Vegetables' as const,
    'Salad Mix': 'Fruits & Vegetables' as const,
    'Unsweetened Applesauce': 'Fruits & Vegetables' as const,
    Carrots: 'Fruits & Vegetables' as const,
    Celery: 'Fruits & Vegetables' as const,
    Onions: 'Fruits & Vegetables' as const,
    Tomatoes: 'Fruits & Vegetables' as const,
    'Chopped Romaine': 'Fruits & Vegetables' as const,
    Lettuce: 'Fruits & Vegetables' as const,
    'Butternut Squash': 'Fruits & Vegetables' as const,
    'Romaine Lettuce': 'Fruits & Vegetables' as const,
    Strawberries: 'Fruits & Vegetables' as const,
    Apple: 'Fruits & Vegetables' as const,
    'Chopped Pecans': 'Fiber, Grains, & Nuts' as const,
    'Old Fashioned Oats': 'Fiber, Grains, & Nuts' as const,
    'Steel Cut Oats': 'Fiber, Grains, & Nuts' as const,
    'Psyllium Flakes': 'Fiber, Grains, & Nuts' as const,
    'Ground Flaxseed': 'Fiber, Grains, & Nuts' as const,
    Pasta: 'Fiber, Grains, & Nuts' as const,
    'Brown Rice': 'Fiber, Grains, & Nuts' as const,
    Quinoa: 'Fiber, Grains, & Nuts' as const,
    Eggs: 'Protein' as const,
    'Chocolate Chips': 'Baking' as const,
    Bacon: 'Protein' as const,
    'Black Pepper': 'Seasoning & Extracts' as const,
    Bananas: 'Fruits & Vegetables' as const,
    Cocoa: 'Baking' as const,
    'Beef': 'Protein' as const,
    'Canned Chicken': 'Protein' as const,
    'Chicken Tenders': 'Protein' as const,
    'THM Creamy Dreamy Hemp Protein': 'Protein' as const,
    'Chicken Breasts': 'Protein' as const,
    'Fish Fillets': 'Protein' as const,
    'Whey Protein': 'Protein' as const,
    'Integral Collagen': 'Protein' as const,
    'Egg Whites': 'Protein' as const,
    'Chicken Bone Broth': 'Broth' as const,
    'Bone Broth': 'Broth' as const,
    'Unflavored Pork Rinds': 'Snack Foods' as const,
    'Hot Sauce': 'Condiments' as const,
    Salsa: 'Condiments' as const,
    'Instant Coffee': 'Beverages' as const,
    'Instant Espresso Powder': 'Beverages' as const,
    'Low Carb Tortillas': 'Breads' as const
};
