export const ingredientMap = {
    'Briana Thomas Baking Mix': 'Baking' as const,
    'THM Baking Blend': 'Baking' as const,
    'Cocoa Powder': 'Baking' as const,
    'Bakers Chocolate': 'Baking' as const,
    'Just Gelatin': 'Baking' as const,
    'Baking Powder': 'Baking' as const,
    'Sugar-free Chocolate Chips': 'Baking' as const,
    'Baking Soda': 'Baking' as const,
    'Inactive Sourdough Starter': 'Baking' as const,
    'Cocoa Butter': 'Baking' as const,
    'Unsweetened Baking Chocolate': 'Baking' as const,
    'Cauliflower Flour': 'Baking' as const,
    Flour: 'Baking' as const,
    Gelatin: 'Baking' as const,
    Cocoa: 'Baking' as const,
    'Instant Yeast': 'Baking' as const,
    'Active Sourdough Starter': 'Baking' as const,
    'Glucomannan Powder': 'Baking' as const,
    'Almond Flour': 'Baking' as const,
    'Sprouted Flour': 'Baking' as const,
    'Coconut Flour': 'Baking' as const,
    'Einkorn Flour': 'Baking' as const,
    'White Whole Wheat Flour': 'Baking' as const,
    'Whole Wheat Flour': 'Baking' as const,
    'Whole Grain Flour': 'Baking' as const,
    'Oat Flour': 'Baking' as const,
    'Salted Caramel Chips': 'Baking' as const,
    'White Chocolate Chips': 'Baking' as const,
    'Sourdough Discard': 'Baking' as const,
    'Coconut Manna': 'Baking' as const,
    'Chocolate Chips': 'Baking' as const,
    'Cinnamon Baking Chips': 'Baking' as const,
    'Peppermint Chips': 'Baking' as const,
    'Black Strap Molasses': 'Baking' as const,
    'Coconut Butter': 'Baking' as const,
    'Unsweetened Coconut Flakes': 'Baking' as const,
    "Coach Betty's Graham Cracker Crumbs": 'Baking' as const,
    Chocolate: 'Baking' as const,
    'Semi-Sweet Chocolate Chips': 'Baking' as const,
    'Coconut Flakes': 'Baking' as const,
    'Raw Honey': 'Seasoning & Extracts' as const,
    Truvia: 'Seasoning & Extracts' as const,
    Pyure: 'Seasoning & Extracts' as const,
    'THM Super Sweet': 'Seasoning & Extracts' as const,
    'THM Gentle Sweet': 'Seasoning & Extracts' as const,
    'Cherry Extract': 'Seasoning & Extracts' as const,
    Stevia: 'Seasoning & Extracts' as const,
    'Chili Powder': 'Seasoning & Extracts' as const,
    Paprika: 'Seasoning & Extracts' as const,
    Cumin: 'Seasoning & Extracts' as const,
    Salt: 'Seasoning & Extracts' as const,
    'THM Duo Greens': 'Seasoning & Extracts' as const,
    'Nutritional Yeast': 'Seasoning & Extracts' as const,
    'Baobab Powder': 'Seasoning & Extracts' as const,
    'Caramel Extract': 'Seasoning & Extracts' as const,
    'Butter Extract': 'Seasoning & Extracts' as const,
    Turmeric: 'Seasoning & Extracts' as const,
    'Curry Powder': 'Seasoning & Extracts' as const,
    'Garlic Powder': 'Seasoning & Extracts' as const,
    'Maple Extract': 'Seasoning & Extracts' as const,
    'Lemon Extract': 'Seasoning & Extracts' as const,
    'Red Pepper Flakes': 'Seasoning & Extracts' as const,
    'Vanilla Extract': 'Seasoning & Extracts' as const,
    'Cinnamon Sticks': 'Seasoning & Extracts' as const,
    'Ground Nutmeg': 'Seasoning & Extracts' as const,
    'Ground Clove': 'Seasoning & Extracts' as const,
    'Onion Powder': 'Seasoning & Extracts' as const,
    'Orange Zest': 'Seasoning & Extracts' as const,
    Parsley: 'Seasoning & Extracts' as const,
    'Cayenne Pepper': 'Seasoning & Extracts' as const,
    Cinnamon: 'Seasoning & Extracts' as const,
    'Almond Extract': 'Seasoning & Extracts' as const,
    'Orange Bitters': 'Seasoning & Extracts' as const,
    'Orange Extract': 'Seasoning & Extracts' as const,
    Basil: 'Seasoning & Extracts' as const,
    'Pumpkin Pie Spice': 'Seasoning & Extracts' as const,
    'Black Pepper': 'Seasoning & Extracts' as const,
    'Garlic Clove': 'Seasoning & Extracts' as const,
    Oregano: 'Seasoning & Extracts' as const,
    'Minced Garlic': 'Seasoning & Extracts' as const,
    'Ground Ginger': 'Seasoning & Extracts' as const,
    'Chopped Garlic': 'Seasoning & Extracts' as const,
    'Pineapple Extract': 'Seasoning & Extracts' as const,
    'Peppermint Extract': 'Seasoning & Extracts' as const,
    'Strawberry Extract': 'Seasoning & Extracts' as const,
    'Liquid Aminos': 'Seasoning & Extracts' as const,
    'Whole Ginger': 'Seasoning & Extracts' as const,
    'Minced Ginger': 'Seasoning & Extracts' as const,
    'Sea Salt': 'Seasoning & Extracts' as const,
    Honey: 'Seasoning & Extracts' as const,
    'Italian Seasoning': 'Seasoning & Extracts' as const,
    'Rum Extract': 'Seasoning & Extracts' as const,
    Cilantro: 'Seasoning & Extracts' as const,
    Pepper: 'Seasoning & Extracts' as const,
    Erythritol: 'Seasoning & Extracts' as const,
    'Cake Batter Extract': 'Seasoning & Extracts' as const,
    'Mineral Salt': 'Seasoning & Extracts' as const,
    'Coconut Extract': 'Seasoning & Extracts' as const,
    Butter: 'Dairy / Non-Dairy' as const,
    "My Montana Kitchen's Sweetened Condensed Milk": 'Dairy / Non-Dairy' as const,
    'Yogurt Cultures': 'Dairy / Non-Dairy' as const,
    'Plain Non-fat Greek Yogurt': 'Dairy / Non-Dairy' as const,
    'Unsweetened Almond Milk': 'Dairy / Non-Dairy' as const,
    'Liquid Eggs': 'Dairy / Non-Dairy' as const,
    'Sweetened Condensed Milk': 'Dairy / Non-Dairy' as const,
    'Blue Cheese Crumbles': 'Dairy / Non-Dairy' as const,
    '1/3-fat Cream Cheese': 'Dairy / Non-Dairy' as const,
    'Low-fat Greek Yogurt': 'Dairy / Non-Dairy' as const,
    'Shredded Cheddar': 'Dairy / Non-Dairy' as const,
    'Low-fat Cottage Cheese': 'Dairy / Non-Dairy' as const,
    'Dairy Free Yogurt': 'Dairy / Non-Dairy' as const,
    'Vegan Butter': 'Dairy / Non-Dairy' as const,
    'Low-fat Cream Cheese': 'Dairy / Non-Dairy' as const,
    'Almond Milk': 'Dairy / Non-Dairy' as const,
    'Cream Cheese': 'Dairy / Non-Dairy' as const,
    'Sour Cream': 'Dairy / Non-Dairy' as const,
    'Low-skim Mozzarella': 'Dairy / Non-Dairy' as const,
    Mozzarella: 'Dairy / Non-Dairy' as const,
    Ricotta: 'Dairy / Non-Dairy' as const,
    'Almond Yogurt': 'Dairy / Non-Dairy' as const,
    'Half and Half': 'Dairy / Non-Dairy' as const,
    'Unsweetened Vanilla Nut Milk': 'Dairy / Non-Dairy' as const,
    'Unsalted Butter': 'Dairy / Non-Dairy' as const,
    'Cashew Milk': 'Dairy / Non-Dairy' as const,
    'Coconut Cream': 'Dairy / Non-Dairy' as const,
    'Goat Cheese': 'Dairy / Non-Dairy' as const,
    'Coconut Milk': 'Dairy / Non-Dairy' as const,
    'Heavy Cream': 'Dairy / Non-Dairy' as const,
    'Flax Milk': 'Dairy / Non-Dairy' as const,
    Ghee: 'Dairy / Non-Dairy' as const,
    'Unsweetened Nut Milk': 'Dairy / Non-Dairy' as const,
    'Nut Milk': 'Dairy / Non-Dairy' as const,
    Yogurt: 'Dairy / Non-Dairy' as const,
    'Olive Oil': 'Vinegar & Oil' as const,
    'Apple Cider Vinegar': 'Vinegar & Oil' as const,
    'Sugar-free Mayonnaise': 'Vinegar & Oil' as const,
    'Greek Yogurt': 'Vinegar & Oil' as const,
    'White Vinegar': 'Vinegar & Oil' as const,
    Mayonnaise: 'Vinegar & Oil' as const,
    'MCT Oil': 'Vinegar & Oil' as const,
    'Easy Balsamic Glaze': 'Vinegar & Oil' as const,
    'Sugar Free Balsamic Vinegar': 'Vinegar & Oil' as const,
    'Balsamic Vinegar': 'Vinegar & Oil' as const,
    'Avocado Oil': 'Vinegar & Oil' as const,
    'High Heat Oil': 'Vinegar & Oil' as const,
    'Coconut Oil': 'Vinegar & Oil' as const,
    'Extra Virgin Coconut Oil': 'Vinegar & Oil' as const,
    Raisins: 'Fruits & Vegetables' as const,
    Avocados: 'Fruits & Vegetables' as const,
    Cauliflower: 'Fruits & Vegetables' as const,
    'Salad Mix': 'Fruits & Vegetables' as const,
    'Unsweetened Applesauce': 'Fruits & Vegetables' as const,
    'Kalamata Olives': 'Fruits & Vegetables' as const,
    Peas: 'Fruits & Vegetables' as const,
    Greenbeans: 'Fruits & Vegetables' as const,
    Peaches: 'Fruits & Vegetables' as const,
    'Frozen Peas/Carrots': 'Fruits & Vegetables' as const,
    'Frozen Greenbeans': 'Fruits & Vegetables' as const,
    Bananas: 'Fruits & Vegetables' as const,
    Carrots: 'Fruits & Vegetables' as const,
    'Yellow Onions': 'Fruits & Vegetables' as const,
    Oranges: 'Fruits & Vegetables' as const,
    Raspberries: 'Fruits & Vegetables' as const,
    'Frozen Raspberries': 'Fruits & Vegetables' as const,
    Celery: 'Fruits & Vegetables' as const,
    'Lime Juice': 'Fruits & Vegetables' as const,
    'Sweet Potatoes': 'Fruits & Vegetables' as const,
    'Dried Blueberries': 'Fruits & Vegetables' as const,
    'Dried Berries': 'Fruits & Vegetables' as const,
    'Red Bell Peppers': 'Fruits & Vegetables' as const,
    Limes: 'Fruits & Vegetables' as const,
    'Canned Diced Tomatoes': 'Fruits & Vegetables' as const,
    Mushrooms: 'Fruits & Vegetables' as const,
    'Canned Diced Tomatoes with Green Chilies': 'Fruits & Vegetables' as const,
    Onions: 'Fruits & Vegetables' as const,
    'Frozen Blueberries': 'Fruits & Vegetables' as const,
    Pumpkin: 'Fruits & Vegetables' as const,
    'Pumpkin Puree': 'Fruits & Vegetables' as const,
    Blueberries: 'Fruits & Vegetables' as const,
    'Small Yellow Potatoes': 'Fruits & Vegetables' as const,
    'Dried Raspberries': 'Fruits & Vegetables' as const,
    'Frozen Strawberries': 'Fruits & Vegetables' as const,
    Lemons: 'Fruits & Vegetables' as const,
    Asparagus: 'Fruits & Vegetables' as const,
    'Lemon Juice': 'Fruits & Vegetables' as const,
    'Extra Virgin Olive Oil': 'Fruits & Vegetables' as const,
    Tomatoes: 'Fruits & Vegetables' as const,
    'Canned Tomato Sauce': 'Fruits & Vegetables' as const,
    'Chopped Romaine': 'Fruits & Vegetables' as const,
    'Frozen Cranberries': 'Fruits & Vegetables' as const,
    Cranberries: 'Fruits & Vegetables' as const,
    Lettuce: 'Fruits & Vegetables' as const,
    'Butternut Squash': 'Fruits & Vegetables' as const,
    'Romaine Lettuce': 'Fruits & Vegetables' as const,
    Eggplants: 'Fruits & Vegetables' as const,
    'Green Bell Peppers': 'Fruits & Vegetables' as const,
    'Gold Yukon Potatoes': 'Fruits & Vegetables' as const,
    Strawberries: 'Fruits & Vegetables' as const,
    Apples: 'Fruits & Vegetables' as const,
    'Chopped Pecans': 'Fiber, Grains, & Nuts' as const,
    'Old Fashioned Oats': 'Fiber, Grains, & Nuts' as const,
    'Quick Cook Steel Cut Oats': 'Fiber, Grains, & Nuts' as const,
    'Steel Cut Oats': 'Fiber, Grains, & Nuts' as const,
    'Psyllium Flakes': 'Fiber, Grains, & Nuts' as const,
    'Ground Flaxseed': 'Fiber, Grains, & Nuts' as const,
    'Brown Rice': 'Fiber, Grains, & Nuts' as const,
    'Frozen Cauliflower Rice': 'Fiber, Grains, & Nuts' as const,
    Quinoa: 'Fiber, Grains, & Nuts' as const,
    'Chopped Walnuts': 'Fiber, Grains, & Nuts' as const,
    Walnuts: 'Fiber, Grains, & Nuts' as const,
    'Mixed Nuts': 'Fiber, Grains, & Nuts' as const,
    'Chai Seeds': 'Fiber, Grains, & Nuts' as const,
    'Raw Pistachios': 'Fiber, Grains, & Nuts' as const,
    'Sunflower Lecithin': 'Fiber, Grains, & Nuts' as const,
    'Almond Slivers': 'Fiber, Grains, & Nuts' as const,
    Eggs: 'Protein' as const,
    Bacon: 'Protein' as const,
    Beef: 'Protein' as const,
    'Canned Tuna': 'Protein' as const,
    'Spicy Italian Sausage': 'Protein' as const,
    'Ground Beef': 'Protein' as const,
    'Red Lentils': 'Protein' as const,
    'Canned Chicken': 'Protein' as const,
    'Ground Lamb': 'Protein' as const,
    'Chicken Tenders': 'Protein' as const,
    'THM Creamy Dreamy Hemp Protein': 'Protein' as const,
    'Chicken Breasts': 'Protein' as const,
    'Turkey Bacon': 'Protein' as const,
    'Pork Chops': 'Protein' as const,
    'Dark Red Kidney Beans': 'Protein' as const,
    'Boneless Skinless Chicken Thighs': 'Protein' as const,
    'Fish Fillets': 'Protein' as const,
    'Venison Sausages': 'Protein' as const,
    'Whey Protein': 'Protein' as const,
    'Integral Collagen': 'Protein' as const,
    'Egg Whites': 'Protein' as const,
    'Refried Beans': 'Protein' as const,
    'Chicken Bone Broth': 'Broth' as const,
    'Chicken Broth': 'Broth' as const,
    'Vegetable Broth': 'Broth' as const,
    'Bone Broth': 'Broth' as const,
    'Unflavored Pork Rinds': 'Snack Foods & Desserts' as const,
    Pretzels: 'Snack Foods & Desserts' as const,
    'Graham Crackers': 'Snack Foods & Desserts' as const,
    Popcorn: 'Snack Foods & Desserts' as const,
    'Hot Sauce': 'Condiments' as const,
    Salsa: 'Condiments' as const,
    'Green Enchilada Sauce': 'Condiments' as const,
    'Pumpkin Spice Syrup': 'Condiments' as const,
    Guacamole: 'Condiments' as const,
    'Yellow Mustard': 'Condiments' as const,
    'Sugar-free Raspberry Jam': 'Condiments' as const,
    'Raspberry Jam': 'Condiments' as const,
    'Instant Coffee': 'Beverages' as const,
    'Instant Espresso Powder': 'Beverages' as const,
    'Instant Decaf Coffee': 'Beverages' as const,
    'Nut Milk Ice Cubes': 'Beverages' as const,
    'Trim Mamarita': 'Beverages' as const,
    Tequila: 'Beverages' as const,
    'Coconut Water': 'Beverages' as const,
    'Irish Whiskey': 'Beverages' as const,
    'Dry Red Wine': 'Beverages' as const,
    Coffee: 'Beverages' as const,
    'Plain Low-fat Kefir': 'Beverages' as const,
    'Chai Tea': 'Beverages' as const,
    'Low Carb Tortillas': 'Breads & Noodles' as const,
    'Zucchini Noodles': 'Breads & Noodles' as const,
    'Elbow Noodles': 'Breads & Noodles' as const,
    'Lasagna Sheets': 'Breads & Noodles' as const,
    'Penne Pasta': 'Breads & Noodles' as const,
    Pasta: 'Breads & Noodles' as const,
    'Chocolate Cake': 'Snack Foods & Desserts' as const,
    'Chocolate Brownies': 'Snack Foods & Desserts' as const,
};
