export const tagMap = {
    'THM E': 'Carbs - "E" Meals',
    'THM S': 'Fats - "S" Meals',
    'THM FP': 'Fuel Pull - "FP" Meals',
    'THM XO': 'Crossover - "XO" Meals',
    'Drinks and Sippers': 'Drinks and Sippers',
    GF: 'Gluten Free',
    'GF Option': '',
    DF: 'Dairy Free',
    'DF Option': '',
    'Keto Friendly': '',
    'Nut Free': '',
    'Nut Free Option': '',
    'Egg Free': '',
    'Apple Free': '',
};
